'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Library_Management_.Library_Management.DLL
Imports Library_Management_.Library_Management.Interface

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication ' MyApplication: هو الذي يقوم بعملية الحقن (The Injector

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Dim usersRepo As IUsersRepository = New UsersRepositorySql()
            Me.MainForm = New frmLogin(usersRepo)
        End Sub

    End Class
End Namespace

'<Global.System.Diagnostics.DebuggerStepThroughAttribute()>
'وظيفة بااختصار
'يتم إنشاء نسخة من مستودع المستخدمين: Dim usersRepo As IUsersRepository = New بحيث يتم تم تمرير هذا المستودع فوراً إلى شاشة الدخول عبر المن
'Protected Overrides Sub OnCreateMainForm() 'يتم إنشاء نسخة من مستودع المستخدمين: Dim usersRepo As IUsersRepository = New
'    Dim usersRepo As IUsersRepository = New UsersRepositorySql()
'    Me.MainForm = New frmLogin(usersRepo) ' تم تمرير هذا المستودع فوراً إلى شاشة الدخول عبر المن
'End Sub
